name: erun
description: A CLI tool to launch iOS simulators and Android emulators with ease. a
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.6.0
  path: ^1.8.0  # Added the path package dependency

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  